/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsIdRouteImport } from './routes/students.$id'
import { Route as BatchesIdRouteImport } from './routes/batches.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesIdRoute = BatchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BatchesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/attendance': typeof AttendanceRoute
  '/backup': typeof BackupRoute
  '/batches': typeof BatchesRouteWithChildren
  '/certificates': typeof CertificatesRoute
  '/history': typeof HistoryRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/batches/$id': typeof BatchesIdRoute
  '/students/$id': typeof StudentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/attendance': typeof AttendanceRoute
  '/backup': typeof BackupRoute
  '/batches': typeof BatchesRouteWithChildren
  '/certificates': typeof CertificatesRoute
  '/history': typeof HistoryRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/batches/$id': typeof BatchesIdRoute
  '/students/$id': typeof StudentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/attendance': typeof AttendanceRoute
  '/backup': typeof BackupRoute
  '/batches': typeof BatchesRouteWithChildren
  '/certificates': typeof CertificatesRoute
  '/history': typeof HistoryRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/batches/$id': typeof BatchesIdRoute
  '/students/$id': typeof StudentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/attendance'
    | '/backup'
    | '/batches'
    | '/certificates'
    | '/history'
    | '/reports'
    | '/settings'
    | '/batches/$id'
    | '/students/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/attendance'
    | '/backup'
    | '/batches'
    | '/certificates'
    | '/history'
    | '/reports'
    | '/settings'
    | '/batches/$id'
    | '/students/$id'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/attendance'
    | '/backup'
    | '/batches'
    | '/certificates'
    | '/history'
    | '/reports'
    | '/settings'
    | '/batches/$id'
    | '/students/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AttendanceRoute: typeof AttendanceRoute
  BackupRoute: typeof BackupRoute
  BatchesRoute: typeof BatchesRouteWithChildren
  CertificatesRoute: typeof CertificatesRoute
  HistoryRoute: typeof HistoryRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StudentsIdRoute: typeof StudentsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$id': {
      id: '/batches/$id'
      path: '/$id'
      fullPath: '/batches/$id'
      preLoaderRoute: typeof BatchesIdRouteImport
      parentRoute: typeof BatchesRoute
    }
  }
}

interface BatchesRouteChildren {
  BatchesIdRoute: typeof BatchesIdRoute
}

const BatchesRouteChildren: BatchesRouteChildren = {
  BatchesIdRoute: BatchesIdRoute,
}

const BatchesRouteWithChildren =
  BatchesRoute._addFileChildren(BatchesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AttendanceRoute: AttendanceRoute,
  BackupRoute: BackupRoute,
  BatchesRoute: BatchesRouteWithChildren,
  CertificatesRoute: CertificatesRoute,
  HistoryRoute: HistoryRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StudentsIdRoute: StudentsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
